"""Event model for system events and observations."""

from __future__ import annotations
from typing import Optional
from datetime import datetime
from sqlalchemy import String, Float, JSON, DateTime, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column
from backend.app.models.base import Base


class Event(Base):
    """A system event generated by the analytics pipeline.

    Event types: detection, zone_crossing, loitering, abandoned_object,
    camera_health, zone_entry, zone_exit, direction_violation, etc.
    """
    __tablename__ = "events"

    id: Mapped[int] = mapped_column(primary_key=True)
    camera_id: Mapped[int] = mapped_column(ForeignKey("cameras.id"), index=True)
    event_type: Mapped[str] = mapped_column(String(50), index=True)
    object_type: Mapped[str] = mapped_column(String(40), default="unknown")
    track_id: Mapped[Optional[str]] = mapped_column(String(80), nullable=True)
    confidence: Mapped[float] = mapped_column(Float, default=0)
    zone_id: Mapped[Optional[int]] = mapped_column(ForeignKey("zones.id"), nullable=True)
    severity: Mapped[float] = mapped_column(Float, default=0.0)
    payload: Mapped[dict] = mapped_column(JSON, default=dict)
    occurred_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow,
        index=True)
